server:
  port: 9006


spring:
  datasource:
    url: jdbc:mysql://localhost:3307/reading
    username: tester
    password: tester
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect