server:
  port: 9001

spring:
  statement: "default profile executing"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/silicon
    username: maninder
    password: maninder
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  profiles: test
  statement: "test profile executing"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/silicon
    username: maninder
    password: maninder
    driver-class-name: com.mysql.cj.jdbc.Driver


---

spring:
  profiles: dev
  statement: "dev profile executing"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/silicon
    username: maninder
    password: maninder
    driver-class-name: com.mysql.cj.jdbc.Driver

