server:
  port: 9001

spring:
  ldap:
    embedded:
      port: 8389
      ldif: classpath:ldap-data.ldif
      base-dn: dc=springframework,dc=org


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/silicon
    username: maninder
    password: maninder
    driver-class-name: com.mysql.cj.jdbc.Driver