server:
  port: 9001

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      okta: DEBUG


okta:
  oauth2:
    issuer: https://dev-65346729.okta.com/oauth2/default
    client-id: 0oa973xcjmqywo7mf5d7
    client-secret: PMuTZM9ScOYpQSr0ufT6x_ZoF5BnTSGyJwbVDH2t

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/silicon
    username: maninder
    password: maninder
    driver-class-name: com.mysql.cj.jdbc.Driver