version: '2'
services:

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: javatechie
      MYSQL_USER: maninder
      MYSQL_PASSWORD: maninder
      MYSQL_ROOT_PASSWORD: root
    networks:
      - kafka-stack-network


networks:
  kafka-stack-network:
    driver: bridge