apiVersion: v1
kind: ConfigMap
metadata:
  name: bookmarker-config
data:
  postgres_host: postgres
  postgres_port: "5432"
  postgres_db_name: appdb

---

apiVersion: v1
kind: Secret
metadata:
  name: bookmarker-secrets
type: Opaque
data:
  postgres_username: cG9zdGdyZXM=
  postgres_password: cG9zdGdyZXM=


