server:
  port: 9003

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

spring:
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: PAYMENT-SERVICE