server:
  port: 9004

spring:
  profiles:
    active: default
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9005
  cloud:
    config:
      profile: default

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost


