server:
  port: 9004

spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: ORDER-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost