version: '2'
services:

  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: reading
      MYSQL_USER: tester
      MYSQL_PASSWORD: tester
      MYSQL_ROOT_PASSWORD: root
    networks:
      - kafka-stack-network2


networks:
  kafka-stack-network2:
    driver: bridge