server:
  port: 9003

#spring:
#  main:
#    web-application-type: none
#  security:
#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: 0oa973xcjmqywo7mf5d7
#            client-secret: PMuTZM9ScOYpQSr0ufT6x_ZoF5BnTSGyJwbVDH2t
#            scope: custom_scope
#            authorization-grant-type: client_credentials
#        provider:
#          okta:
#            token-uri: https://dev-65346729.okta.com/oauth2/default/v1/token
