name: JAVA CICD with maven

on:
  push:
    branches: [ CRUD_kubernetes_pipeline ]
  pull_request:
    branches: [ CRUD_kubernetes_pipeline ]


jobs:

  build:
    runs-on: ubuntu-latest
    name: Run mvn build and generate coverage report

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean install

      - name: Test cases execution
        run: mvn clean test

#      - if: ${{ github.ref == 'refs/heads/feature/CRUD_kubernetes_pipeline'}}
      - name: Build and Publish Docker Image
        run: |
          echo "This job runs in custom branch"
            ./mvnw clean package jib:dockerBuild -DskipTests
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker tag maninder40407/crud-kubernetes maninder40407/crud-kubernetes:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/maninder40407/crud-kubernetes:latest


