# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build

on:
  push:
    branches: [ "**" ] #** means on any branch when we push, run the pipeline
#  pull_request:
#    branches: [ "main" ]  #**not raising PR so commenting out this code. This line means when some
#    #raise PR again main branch, run the pipeline.

#permissions:
#  contents: read

jobs:
  #  build-bookmarker-api:
  #    name: Build bookmarker-api
  runs-on: ubuntu-latest
  #    defaults:
  #      run:
  #        working-directory: .

  steps:
    - uses: actions/checkout@v3

    - name: 'Setup JDK 17'
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'openjdk'
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw verify

    - if: ${{ github.ref == 'ref/heads/feature/main' }}
      name: Build and Publish Docker Image
      run: |
        ./mvnw clean package jib:dockerBuild -DskipTests
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }} /bookmarker-api